# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dea0c3fc54aac24957d7d1970845b54ba4d1ee84abc553bf44ac77e9f9dd06141fb0d8b758f9420f35bdafa131773e802f3a426b8e3e667f4266cdec8ac7f07

test:
  secret_key_base: 71dbbff80d46701db11dc847f6bff844b13918e711b332f2bda44e60b159eb0b295218d20e50dfc16f472e2158378d14182eed961395816eeeb0823992066300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
